INSERT INTO SITE (ID, NAME, DOMAIN) VALUES (1, 'Goldenline', 'http://www.goldenline.pl');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(1,1,'http://www.goldenline.pl/praca/administracja-panstwowa','Administracja Państwowa');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(2,1,'http://www.goldenline.pl/praca/administracja-biurowa','Administracja biurowa');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(3,1,'http://www.goldenline.pl/praca/analiza','Analiza');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(4,1,'http://www.goldenline.pl/praca/architektura','Architektura');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(5,1,'http://www.goldenline.pl/praca/badania-i-rozwoj','Badania i rozwój');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(6,1,'http://www.goldenline.pl/praca/budownictwo-geodezja','Budownictwo/Geodezja');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(7,1,'http://www.goldenline.pl/praca/doradztwo-konsulting','Doradztwo/Konsulting');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(8,1,'http://www.goldenline.pl/praca/energetyka-gazownictwo','Energetyka/Gazownictwo');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(9,1,'http://www.goldenline.pl/praca/farmaceutyka-biotechnologia','Farmaceutyka/Biotechnologia');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(10,1,'http://www.goldenline.pl/praca/finanse-ekonomia','Finanse/Ekonomia');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(11,1,'http://www.goldenline.pl/praca/geologia-hydrologia-tektonika','Geologia/Hydrologia/Tektonika');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(12,1,'http://www.goldenline.pl/praca/grafika-kreacja-artystyczna-fotografia','Grafika/Kreacja artystyczna/Fotografia');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(13,1,'http://www.goldenline.pl/praca/hotelarstwo-turystyka-katering','Hotelarstwo/Turystyka/Katering');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(14,1,'http://www.goldenline.pl/praca/human-resources','Human Resources');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(15,1,'http://www.goldenline.pl/praca/informatyka-administracja','Informatyka/Administracja');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(16,1,'http://www.goldenline.pl/praca/informatyka-programowanie','Informatyka/Programowanie');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(17,1,'http://www.goldenline.pl/praca/inne','Inne');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(18,1,'http://www.goldenline.pl/praca/instalacja-utrzymanie-serwis','Instalacja/Utrzymanie/Serwis');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(19,1,'http://www.goldenline.pl/praca/internet-e-commerce','Internet/E-Commerce');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(20,1,'http://www.goldenline.pl/praca/inzynieria-elektronika-technologia','Inżynieria/Elektronika/Technologia');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(21,1,'http://www.goldenline.pl/praca/kadra-zarzadzajaca','Kadra zarządzająca');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(22,1,'http://www.goldenline.pl/praca/kontrola-jakosci-bhp','Kontrola jakości/BHP');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(23,1,'http://www.goldenline.pl/praca/ksiegowosc-audyt-podatki','Księgowość/Audyt/Podatki');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(24,1,'http://www.goldenline.pl/praca/logistyka-transport-dystrybucja','Logistyka/Transport/Dystrybucja');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(25,1,'http://www.goldenline.pl/praca/marketing-reklama-public-relations','Marketing/Reklama/Public Relations');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(26,1,'http://www.goldenline.pl/praca/media-sztuka-rozrywka','Media/Sztuka/Rozrywka');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(27,1,'http://www.goldenline.pl/praca/medycyna','Medycyna');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(28,1,'http://www.goldenline.pl/praca/motoryzacja','Motoryzacja');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(29,1,'http://www.goldenline.pl/praca/nieruchomosci-budownictwo','Nieruchomości/Budownictwo');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(30,1,'http://www.goldenline.pl/praca/obsluga-klienta-call-center','Obsługa klienta/Call Center');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(31,1,'http://www.goldenline.pl/praca/ochrona-osob-i-mienia','Ochrona osób i mienia');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(32,1,'http://www.goldenline.pl/praca/organizacje-pozarzadowe-wolontariat','Organizacje pozarządowe/Wolontariat');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(33,1,'http://www.goldenline.pl/praca/praca-fizyczna','Praca fizyczna');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(34,1,'http://www.goldenline.pl/praca/praktyki','Praktyki');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(35,1,'http://www.goldenline.pl/praca/prawo','Prawo');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(36,1,'http://www.goldenline.pl/praca/produkcja','Produkcja');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(37,1,'http://www.goldenline.pl/praca/projektowanie-wdrazanie','Projektowanie/Wdrażanie');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(38,1,'http://www.goldenline.pl/praca/rolnictwo-ochrona-srodowiska','Rolnictwo/Ochrona środowiska');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(39,1,'http://www.goldenline.pl/praca/sport-rekreacja','Sport/Rekreacja');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(40,1,'http://www.goldenline.pl/praca/sprzedaz','Sprzedaż');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(41,1,'http://www.goldenline.pl/praca/staze','Staże');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(42,1,'http://www.goldenline.pl/praca/szkolenia-edukacja','Szkolenia/Edukacja');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(43,1,'http://www.goldenline.pl/praca/sluzba-zdrowia','Służba zdrowia');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(44,1,'http://www.goldenline.pl/praca/telekomunikacja','Telekomunikacja');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(45,1,'http://www.goldenline.pl/praca/tlumaczenia','Tłumaczenia');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(46,1,'http://www.goldenline.pl/praca/ubezpieczenia','Ubezpieczenia');
INSERT INTO CATEGORY(ID, SITE_ID, URL, NAME) VALUES(47,1,'http://www.goldenline.pl/praca/zakupy','Zakupy');
